/**
 * Catálogo de cuentas sectoriales — Fase 2H (§H3 agropecuario, §H4 sin fines de
 * lucro, más los deltas de industria y servicios).
 *
 * Marco normativo: RT 54, texto ordenado por RT 59 (Norma Unificada Argentina).
 * Las denominaciones siguen el vocabulario de la norma vigente; los modelos
 * derogados de RT 8/9/11 se usan sólo como antecedente pedagógico.
 *
 * Cada cuenta trae los metadatos que el motor necesita para exponerla sin
 * intervención manual: rubro (`statementGroup`), corriente/no corriente,
 * clasificación monetaria para la reexpresión, categoría de EFE, función del
 * gasto, nota y anexo. Sin estos metadatos la cuenta existiría pero no llegaría
 * a los estados.
 *
 * Rangos de código elegidos para no colisionar con el núcleo:
 *   1.1.07 / 1.2.06  activos biológicos          (agro)
 *   1.1.08           producción y productos agro (agro)
 *   4.1.06 / 4.3.06  ingresos y costo agro       (agro)
 *   4.6.10           resultados de producción y tenencia agro
 *   1.1.09           créditos por cuotas sociales (ONG)
 *   2.1.08 / 2.2.03  fondos con destino específico (ONG)
 *   3.5              patrimonio de entidades sin fines de lucro
 *   4.1.10           recursos (ONG)
 *   4.5.10 / 4.4.10  gastos institucionales y de programas (ONG)
 *   1.1.10 / 4.3.07  producción en proceso y costos (industria y servicios)
 */

import type { SectorAccountDefinition } from './types'

// ─────────────────────────────────────────────────────────────
// Agropecuario (RT 54 §5.11 — activos biológicos y productos agropecuarios)
// ─────────────────────────────────────────────────────────────

const AGRICULTURAL: SectorAccountDefinition[] = [
    // ── Activos biológicos corrientes ────────────────────────
    {
        code: '1.1.07',
        name: 'Activos biológicos corrientes',
        kind: 'ASSET',
        section: 'CURRENT',
        group: 'Activos biológicos',
        statementGroup: 'INVENTORIES',
        parentCode: '1.1',
        isHeader: true,
        currentClassification: 'CURRENT',
        monetaryClassification: 'NON_MONETARY',
        notesGroup: 'Activos biológicos',
        annexGroup: 'Activos biológicos',
        profile: 'AGRICULTURAL',
        hint: 'Animales y plantas vivos que se consumirán o venderán dentro del ejercicio.',
    },
    {
        code: '1.1.07.01',
        name: 'Activos biológicos en crecimiento',
        kind: 'ASSET',
        section: 'CURRENT',
        group: 'Activos biológicos',
        statementGroup: 'INVENTORIES',
        parentCode: '1.1.07',
        currentClassification: 'CURRENT',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        notesGroup: 'Activos biológicos',
        annexGroup: 'Activos biológicos',
        profile: 'AGRICULTURAL',
        hint: 'Aún no alcanzaron el punto de cosecha, recolección o faena.',
    },
    {
        code: '1.1.07.02',
        name: 'Activos biológicos en desarrollo',
        kind: 'ASSET',
        section: 'CURRENT',
        group: 'Activos biológicos',
        statementGroup: 'INVENTORIES',
        parentCode: '1.1.07',
        currentClassification: 'CURRENT',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        notesGroup: 'Activos biológicos',
        annexGroup: 'Activos biológicos',
        profile: 'AGRICULTURAL',
    },
    {
        code: '1.1.07.03',
        name: 'Activos biológicos terminados destinados a la venta',
        kind: 'ASSET',
        section: 'CURRENT',
        group: 'Activos biológicos',
        statementGroup: 'INVENTORIES',
        parentCode: '1.1.07',
        currentClassification: 'CURRENT',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        notesGroup: 'Activos biológicos',
        annexGroup: 'Activos biológicos',
        profile: 'AGRICULTURAL',
        hint: 'Completaron su proceso de desarrollo y están listos para su venta.',
    },
    {
        code: '1.1.07.90',
        name: 'Desvalorización de activos biológicos corrientes',
        kind: 'ASSET',
        section: 'CURRENT',
        group: 'Activos biológicos',
        statementGroup: 'INVENTORIES',
        parentCode: '1.1.07',
        isContra: true,
        normalSide: 'CREDIT',
        currentClassification: 'CURRENT',
        monetaryClassification: 'NON_MONETARY',
        notesGroup: 'Activos biológicos',
        annexGroup: 'Activos biológicos',
        profile: 'AGRICULTURAL',
        hint: 'Regularizadora: reduce la medición del activo biológico corriente.',
    },

    // ── Productos agropecuarios y producción ─────────────────
    {
        code: '1.1.08',
        name: 'Productos agropecuarios',
        kind: 'ASSET',
        section: 'CURRENT',
        group: 'Bienes de cambio',
        statementGroup: 'INVENTORIES',
        parentCode: '1.1',
        isHeader: true,
        currentClassification: 'CURRENT',
        monetaryClassification: 'NON_MONETARY',
        notesGroup: 'Bienes de cambio',
        annexGroup: 'Costo de ventas',
        profile: 'AGRICULTURAL',
        hint: 'Productos obtenidos al momento de la cosecha, recolección, faena u obtención.',
    },
    {
        code: '1.1.08.01',
        name: 'Productos agropecuarios obtenidos',
        kind: 'ASSET',
        section: 'CURRENT',
        group: 'Bienes de cambio',
        statementGroup: 'INVENTORIES',
        parentCode: '1.1.08',
        currentClassification: 'CURRENT',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        notesGroup: 'Bienes de cambio',
        annexGroup: 'Costo de ventas',
        profile: 'AGRICULTURAL',
    },
    {
        code: '1.1.08.02',
        name: 'Materias primas e insumos agropecuarios',
        kind: 'ASSET',
        section: 'CURRENT',
        group: 'Bienes de cambio',
        statementGroup: 'INVENTORIES',
        parentCode: '1.1.08',
        currentClassification: 'CURRENT',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        notesGroup: 'Bienes de cambio',
        annexGroup: 'Costo de ventas',
        profile: 'AGRICULTURAL',
        hint: 'Semillas, agroquímicos, fertilizantes, alimentos balanceados y similares.',
    },
    {
        code: '1.1.08.03',
        name: 'Producción agropecuaria en proceso',
        kind: 'ASSET',
        section: 'CURRENT',
        group: 'Bienes de cambio',
        statementGroup: 'INVENTORIES',
        parentCode: '1.1.08',
        currentClassification: 'CURRENT',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        notesGroup: 'Bienes de cambio',
        annexGroup: 'Costo de ventas',
        profile: 'AGRICULTURAL',
        hint: 'Sementeras y trabajos culturales aplicados que aún no produjeron cosecha.',
    },

    // ── Activos biológicos no corrientes (factor de producción) ──
    {
        code: '1.2.06',
        name: 'Activos biológicos no corrientes',
        kind: 'ASSET',
        section: 'NON_CURRENT',
        group: 'Activos biológicos',
        statementGroup: 'PPE',
        parentCode: '1.2',
        isHeader: true,
        currentClassification: 'NON_CURRENT',
        monetaryClassification: 'NON_MONETARY',
        notesGroup: 'Activos biológicos',
        annexGroup: 'Activos biológicos',
        profile: 'AGRICULTURAL',
        hint: 'Activos biológicos utilizados como factor de producción (no destinados a la venta).',
    },
    {
        code: '1.2.06.01',
        name: 'Hacienda reproductora',
        kind: 'ASSET',
        section: 'NON_CURRENT',
        group: 'Activos biológicos',
        statementGroup: 'PPE',
        parentCode: '1.2.06',
        currentClassification: 'NON_CURRENT',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'INVESTING',
        notesGroup: 'Activos biológicos',
        annexGroup: 'Activos biológicos',
        profile: 'AGRICULTURAL',
    },
    {
        code: '1.2.06.02',
        name: 'Plantaciones permanentes',
        kind: 'ASSET',
        section: 'NON_CURRENT',
        group: 'Activos biológicos',
        statementGroup: 'PPE',
        parentCode: '1.2.06',
        currentClassification: 'NON_CURRENT',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'INVESTING',
        notesGroup: 'Activos biológicos',
        annexGroup: 'Activos biológicos',
        profile: 'AGRICULTURAL',
        hint: 'Montes frutales, forestaciones y cultivos perennes en producción.',
    },
    {
        code: '1.2.06.90',
        name: 'Depreciación acumulada de activos biológicos no corrientes',
        kind: 'ASSET',
        section: 'NON_CURRENT',
        group: 'Activos biológicos',
        statementGroup: 'PPE',
        parentCode: '1.2.06',
        isContra: true,
        normalSide: 'CREDIT',
        currentClassification: 'NON_CURRENT',
        monetaryClassification: 'NON_MONETARY',
        notesGroup: 'Activos biológicos',
        annexGroup: 'Activos biológicos',
        profile: 'AGRICULTURAL',
    },

    // ── Resultados ───────────────────────────────────────────
    {
        code: '4.1.06',
        name: 'Ventas de productos agropecuarios',
        kind: 'INCOME',
        section: 'OPERATING',
        group: 'Ingresos operativos',
        statementGroup: 'SALES',
        parentCode: '4.1',
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        notesGroup: 'Ingresos',
        profile: 'AGRICULTURAL',
    },
    {
        code: '4.3.06',
        name: 'Costo de productos agropecuarios vendidos',
        kind: 'EXPENSE',
        section: 'COST',
        group: 'Costo de ventas',
        statementGroup: 'COGS',
        parentCode: '4.3',
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        notesGroup: 'Costo de ventas',
        annexGroup: 'Costo de ventas',
        profile: 'AGRICULTURAL',
    },
    {
        code: '4.6.10',
        name: 'Resultado por producción agropecuaria',
        kind: 'INCOME',
        section: 'OPERATING',
        group: 'Resultados de producción',
        statementGroup: 'OTHER_OPERATING_INCOME',
        parentCode: '4.6',
        allowOppositeBalance: true,
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        notesGroup: 'Resultados de producción',
        profile: 'AGRICULTURAL',
        hint: 'Resultado del crecimiento vegetativo y la transformación biológica, con independencia de la venta.',
    },
    {
        code: '4.6.11',
        name: 'Resultado por tenencia de activos biológicos',
        kind: 'INCOME',
        section: 'OPERATING',
        group: 'Resultados de producción',
        statementGroup: 'OTHER_OPERATING_INCOME',
        parentCode: '4.6',
        allowOppositeBalance: true,
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        notesGroup: 'Resultados de producción',
        profile: 'AGRICULTURAL',
        hint: 'Cambio de valor por variaciones de precio de mercado, separado del resultado de producción.',
    },
    {
        code: '4.7.10',
        name: 'Pérdidas por mortandad y mermas',
        kind: 'EXPENSE',
        section: 'OTHER',
        group: 'Otros egresos',
        statementGroup: 'OTHER_EXPENSES',
        parentCode: '4.7',
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        resultFunction: 'PRODUCTION',
        notesGroup: 'Otros egresos',
        profile: 'AGRICULTURAL',
    },
    {
        code: '4.7.11',
        name: 'Subsidios y ayudas a la actividad agropecuaria',
        kind: 'INCOME',
        section: 'OTHER',
        group: 'Otros ingresos',
        statementGroup: 'OTHER_INCOME',
        parentCode: '4.7',
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        notesGroup: 'Otros ingresos',
        profile: 'AGRICULTURAL',
    },
]

// ─────────────────────────────────────────────────────────────
// Industria y servicios (costos de producción y de prestación)
// ─────────────────────────────────────────────────────────────

const INDUSTRIAL: SectorAccountDefinition[] = [
    {
        code: '1.1.10',
        name: 'Producción en proceso',
        kind: 'ASSET',
        section: 'CURRENT',
        group: 'Bienes de cambio',
        statementGroup: 'INVENTORIES',
        parentCode: '1.1',
        isHeader: true,
        currentClassification: 'CURRENT',
        monetaryClassification: 'NON_MONETARY',
        notesGroup: 'Bienes de cambio',
        annexGroup: 'Costo de ventas',
        profile: 'INDUSTRIAL',
    },
    {
        code: '1.1.10.01',
        name: 'Materias primas',
        kind: 'ASSET',
        section: 'CURRENT',
        group: 'Bienes de cambio',
        statementGroup: 'INVENTORIES',
        parentCode: '1.1.10',
        currentClassification: 'CURRENT',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        notesGroup: 'Bienes de cambio',
        annexGroup: 'Costo de ventas',
        profile: 'INDUSTRIAL',
    },
    {
        code: '1.1.10.02',
        name: 'Productos en proceso',
        kind: 'ASSET',
        section: 'CURRENT',
        group: 'Bienes de cambio',
        statementGroup: 'INVENTORIES',
        parentCode: '1.1.10',
        currentClassification: 'CURRENT',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        notesGroup: 'Bienes de cambio',
        annexGroup: 'Costo de ventas',
        profile: 'INDUSTRIAL',
    },
    {
        code: '1.1.10.03',
        name: 'Productos terminados',
        kind: 'ASSET',
        section: 'CURRENT',
        group: 'Bienes de cambio',
        statementGroup: 'INVENTORIES',
        parentCode: '1.1.10',
        currentClassification: 'CURRENT',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        notesGroup: 'Bienes de cambio',
        annexGroup: 'Costo de ventas',
        profile: 'INDUSTRIAL',
    },
    {
        code: '4.3.07',
        name: 'Costos de producción',
        kind: 'EXPENSE',
        section: 'COST',
        group: 'Costo de producción',
        statementGroup: 'COGS',
        parentCode: '4.3',
        isHeader: true,
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        resultFunction: 'PRODUCTION',
        notesGroup: 'Costo de ventas',
        annexGroup: 'Costo de producción',
        profile: 'INDUSTRIAL',
    },
    {
        code: '4.3.07.01',
        name: 'Mano de obra directa',
        kind: 'EXPENSE',
        section: 'COST',
        group: 'Costo de producción',
        statementGroup: 'COGS',
        parentCode: '4.3.07',
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        resultFunction: 'PRODUCTION',
        annexGroup: 'Costo de producción',
        profile: 'INDUSTRIAL',
    },
    {
        code: '4.3.07.02',
        name: 'Materiales e insumos directos',
        kind: 'EXPENSE',
        section: 'COST',
        group: 'Costo de producción',
        statementGroup: 'COGS',
        parentCode: '4.3.07',
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        resultFunction: 'PRODUCTION',
        annexGroup: 'Costo de producción',
        profile: 'INDUSTRIAL',
    },
    {
        code: '4.3.07.03',
        name: 'Costos indirectos de producción',
        kind: 'EXPENSE',
        section: 'COST',
        group: 'Costo de producción',
        statementGroup: 'COGS',
        parentCode: '4.3.07',
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        resultFunction: 'PRODUCTION',
        annexGroup: 'Costo de producción',
        profile: 'INDUSTRIAL',
    },
    {
        code: '4.3.07.04',
        name: 'Depreciaciones afectadas a producción',
        kind: 'EXPENSE',
        section: 'COST',
        group: 'Costo de producción',
        statementGroup: 'COGS',
        parentCode: '4.3.07',
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'NOT_APPLICABLE',
        resultFunction: 'PRODUCTION',
        annexGroup: 'Costo de producción',
        profile: 'INDUSTRIAL',
        hint: 'No implica movimiento de efectivo: se ajusta en el EFE por el método indirecto.',
    },
]

const SERVICES: SectorAccountDefinition[] = [
    {
        code: '4.3.08',
        name: 'Costo de los servicios prestados',
        kind: 'EXPENSE',
        section: 'COST',
        group: 'Costo de servicios',
        statementGroup: 'COGS',
        parentCode: '4.3',
        isHeader: true,
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        resultFunction: 'PRODUCTION',
        notesGroup: 'Costo de ventas',
        annexGroup: 'Costo de servicios',
        profile: 'SERVICES',
    },
    {
        code: '4.3.08.01',
        name: 'Mano de obra afectada a servicios',
        kind: 'EXPENSE',
        section: 'COST',
        group: 'Costo de servicios',
        statementGroup: 'COGS',
        parentCode: '4.3.08',
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        resultFunction: 'PRODUCTION',
        annexGroup: 'Costo de servicios',
        profile: 'SERVICES',
    },
    {
        code: '4.3.08.02',
        name: 'Insumos y costos directos de servicios',
        kind: 'EXPENSE',
        section: 'COST',
        group: 'Costo de servicios',
        statementGroup: 'COGS',
        parentCode: '4.3.08',
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        resultFunction: 'PRODUCTION',
        annexGroup: 'Costo de servicios',
        profile: 'SERVICES',
    },
    {
        code: '4.3.08.03',
        name: 'Costos indirectos atribuibles a servicios',
        kind: 'EXPENSE',
        section: 'COST',
        group: 'Costo de servicios',
        statementGroup: 'COGS',
        parentCode: '4.3.08',
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        resultFunction: 'PRODUCTION',
        annexGroup: 'Costo de servicios',
        profile: 'SERVICES',
    },
]

// ─────────────────────────────────────────────────────────────
// Entidades sin fines de lucro
// ─────────────────────────────────────────────────────────────

const NONPROFIT: SectorAccountDefinition[] = [
    {
        code: '1.1.09',
        name: 'Créditos por cuotas sociales',
        kind: 'ASSET',
        section: 'CURRENT',
        group: 'Créditos',
        statementGroup: 'OTHER_RECEIVABLES',
        parentCode: '1.1',
        isHeader: true,
        currentClassification: 'CURRENT',
        monetaryClassification: 'MONETARY',
        notesGroup: 'Créditos',
        profile: 'NONPROFIT',
    },
    {
        code: '1.1.09.01',
        name: 'Cuotas sociales a cobrar',
        kind: 'ASSET',
        section: 'CURRENT',
        group: 'Créditos',
        statementGroup: 'OTHER_RECEIVABLES',
        parentCode: '1.1.09',
        currentClassification: 'CURRENT',
        monetaryClassification: 'MONETARY',
        cashFlowCategory: 'OPERATING',
        notesGroup: 'Créditos',
        profile: 'NONPROFIT',
    },
    {
        code: '1.1.09.02',
        name: 'Subsidios y aportes a percibir',
        kind: 'ASSET',
        section: 'CURRENT',
        group: 'Créditos',
        statementGroup: 'OTHER_RECEIVABLES',
        parentCode: '1.1.09',
        currentClassification: 'CURRENT',
        monetaryClassification: 'MONETARY',
        cashFlowCategory: 'OPERATING',
        notesGroup: 'Créditos',
        profile: 'NONPROFIT',
    },
    {
        code: '1.1.09.90',
        name: 'Previsión por cuotas sociales incobrables',
        kind: 'ASSET',
        section: 'CURRENT',
        group: 'Créditos',
        statementGroup: 'OTHER_RECEIVABLES',
        parentCode: '1.1.09',
        isContra: true,
        normalSide: 'CREDIT',
        currentClassification: 'CURRENT',
        monetaryClassification: 'MONETARY',
        notesGroup: 'Créditos',
        profile: 'NONPROFIT',
    },

    // ── Obligaciones por recursos con destino específico ─────
    {
        code: '2.1.08',
        name: 'Fondos con destino específico a aplicar',
        kind: 'LIABILITY',
        section: 'CURRENT',
        group: 'Otras deudas',
        statementGroup: 'DEFERRED_INCOME',
        parentCode: '2.1',
        isHeader: true,
        currentClassification: 'CURRENT',
        monetaryClassification: 'MONETARY',
        notesGroup: 'Fondos con destino específico',
        profile: 'NONPROFIT',
        hint: 'Recursos recibidos con una afectación que la entidad todavía no cumplió.',
    },
    {
        code: '2.1.08.01',
        name: 'Subsidios con cargo de rendición',
        kind: 'LIABILITY',
        section: 'CURRENT',
        group: 'Otras deudas',
        statementGroup: 'DEFERRED_INCOME',
        parentCode: '2.1.08',
        currentClassification: 'CURRENT',
        monetaryClassification: 'MONETARY',
        cashFlowCategory: 'OPERATING',
        notesGroup: 'Fondos con destino específico',
        profile: 'NONPROFIT',
    },
    {
        code: '2.1.08.02',
        name: 'Donaciones con afectación específica',
        kind: 'LIABILITY',
        section: 'CURRENT',
        group: 'Otras deudas',
        statementGroup: 'DEFERRED_INCOME',
        parentCode: '2.1.08',
        currentClassification: 'CURRENT',
        monetaryClassification: 'MONETARY',
        cashFlowCategory: 'OPERATING',
        notesGroup: 'Fondos con destino específico',
        profile: 'NONPROFIT',
    },
    {
        code: '2.1.08.03',
        name: 'Cuotas sociales cobradas por adelantado',
        kind: 'LIABILITY',
        section: 'CURRENT',
        group: 'Otras deudas',
        statementGroup: 'DEFERRED_INCOME',
        parentCode: '2.1.08',
        currentClassification: 'CURRENT',
        monetaryClassification: 'MONETARY',
        cashFlowCategory: 'OPERATING',
        notesGroup: 'Fondos con destino específico',
        profile: 'NONPROFIT',
    },

    // ── Patrimonio ───────────────────────────────────────────
    {
        code: '3.5',
        name: 'Patrimonio de entidades sin fines de lucro',
        kind: 'EQUITY',
        section: 'CURRENT',
        group: 'Patrimonio social',
        statementGroup: 'CAPITAL',
        parentCode: '3',
        isHeader: true,
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        equityComponent: 'CAPITAL',
        notesGroup: 'Patrimonio',
        profile: 'NONPROFIT',
    },
    {
        code: '3.5.01',
        name: 'Capital social o fondo fundacional',
        kind: 'EQUITY',
        section: 'CURRENT',
        group: 'Patrimonio social',
        statementGroup: 'CAPITAL',
        parentCode: '3.5',
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        equityComponent: 'CAPITAL',
        cashFlowCategory: 'FINANCING',
        notesGroup: 'Patrimonio',
        profile: 'NONPROFIT',
    },
    {
        code: '3.5.02',
        name: 'Fondos con restricciones permanentes',
        kind: 'EQUITY',
        section: 'CURRENT',
        group: 'Patrimonio social',
        statementGroup: 'RESERVES',
        parentCode: '3.5',
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        equityComponent: 'OTHER_RESERVE',
        notesGroup: 'Patrimonio',
        profile: 'NONPROFIT',
        hint: 'Patrimonio afectado a un destino que la entidad no puede modificar.',
    },
    {
        code: '3.5.03',
        name: 'Superávit o déficit acumulado',
        kind: 'EQUITY',
        section: 'CURRENT',
        group: 'Patrimonio social',
        statementGroup: 'RETAINED_EARNINGS',
        parentCode: '3.5',
        allowOppositeBalance: true,
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        equityComponent: 'PRIOR_RETAINED_EARNINGS',
        notesGroup: 'Patrimonio',
        profile: 'NONPROFIT',
    },
    {
        code: '3.5.04',
        name: 'Bienes recibidos por donación',
        kind: 'EQUITY',
        section: 'CURRENT',
        group: 'Patrimonio social',
        statementGroup: 'CAPITAL',
        parentCode: '3.5',
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        equityComponent: 'CAPITAL',
        notesGroup: 'Patrimonio',
        profile: 'NONPROFIT',
    },

    // ── Recursos ─────────────────────────────────────────────
    {
        code: '4.1.10',
        name: 'Recursos',
        kind: 'INCOME',
        section: 'OPERATING',
        group: 'Recursos',
        statementGroup: 'SALES',
        parentCode: '4.1',
        isHeader: true,
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        notesGroup: 'Recursos',
        profile: 'NONPROFIT',
        hint: 'Equivalente funcional de los ingresos: no son ventas ni resultado comercial.',
    },
    {
        code: '4.1.10.01',
        name: 'Cuotas de asociados',
        kind: 'INCOME',
        section: 'OPERATING',
        group: 'Recursos',
        statementGroup: 'SALES',
        parentCode: '4.1.10',
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        notesGroup: 'Recursos',
        profile: 'NONPROFIT',
    },
    {
        code: '4.1.10.02',
        name: 'Donaciones y contribuciones para fines generales',
        kind: 'INCOME',
        section: 'OPERATING',
        group: 'Recursos',
        statementGroup: 'SALES',
        parentCode: '4.1.10',
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        notesGroup: 'Recursos',
        profile: 'NONPROFIT',
    },
    {
        code: '4.1.10.03',
        name: 'Recursos con destino específico devengados',
        kind: 'INCOME',
        section: 'OPERATING',
        group: 'Recursos',
        statementGroup: 'SALES',
        parentCode: '4.1.10',
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        notesGroup: 'Recursos',
        profile: 'NONPROFIT',
        hint: 'Se reconocen cuando se cumple la afectación comprometida.',
    },
    {
        code: '4.1.10.04',
        name: 'Subsidios y aportes del Estado',
        kind: 'INCOME',
        section: 'OPERATING',
        group: 'Recursos',
        statementGroup: 'SALES',
        parentCode: '4.1.10',
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        notesGroup: 'Recursos',
        profile: 'NONPROFIT',
    },
    {
        code: '4.1.10.05',
        name: 'Recursos por campañas de recaudación',
        kind: 'INCOME',
        section: 'OPERATING',
        group: 'Recursos',
        statementGroup: 'SALES',
        parentCode: '4.1.10',
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        notesGroup: 'Recursos',
        profile: 'NONPROFIT',
    },
    {
        code: '4.1.10.06',
        name: 'Recursos por prestaciones a asociados',
        kind: 'INCOME',
        section: 'OPERATING',
        group: 'Recursos',
        statementGroup: 'SALES',
        parentCode: '4.1.10',
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        notesGroup: 'Recursos',
        profile: 'NONPROFIT',
    },

    // ── Gastos ───────────────────────────────────────────────
    {
        code: '4.4.10',
        name: 'Gastos de programas y actividades',
        kind: 'EXPENSE',
        section: 'SELLING',
        group: 'Gastos de actividades',
        statementGroup: 'SELLING_EXPENSES',
        parentCode: '4.4',
        isHeader: true,
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        resultFunction: 'SELLING',
        notesGroup: 'Gastos',
        annexGroup: 'Gastos por función',
        profile: 'NONPROFIT',
        hint: 'Gastos directamente aplicados al objeto social de la entidad.',
    },
    {
        code: '4.4.10.01',
        name: 'Gastos de actividades deportivas',
        kind: 'EXPENSE',
        section: 'SELLING',
        group: 'Gastos de actividades',
        statementGroup: 'SELLING_EXPENSES',
        parentCode: '4.4.10',
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        resultFunction: 'SELLING',
        annexGroup: 'Gastos por función',
        profile: 'NONPROFIT',
    },
    {
        code: '4.4.10.02',
        name: 'Gastos de actividades sociales y culturales',
        kind: 'EXPENSE',
        section: 'SELLING',
        group: 'Gastos de actividades',
        statementGroup: 'SELLING_EXPENSES',
        parentCode: '4.4.10',
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        resultFunction: 'SELLING',
        annexGroup: 'Gastos por función',
        profile: 'NONPROFIT',
    },
    {
        code: '4.4.10.03',
        name: 'Gastos de programas educativos',
        kind: 'EXPENSE',
        section: 'SELLING',
        group: 'Gastos de actividades',
        statementGroup: 'SELLING_EXPENSES',
        parentCode: '4.4.10',
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        resultFunction: 'SELLING',
        annexGroup: 'Gastos por función',
        profile: 'NONPROFIT',
    },
    {
        // 4.5.10 ya existe en el núcleo ("Impuestos y tasas"): se usa 4.5.20 para
        // no colgar los gastos institucionales de un rubro ajeno.
        code: '4.5.20',
        name: 'Gastos institucionales y de administración',
        kind: 'EXPENSE',
        section: 'ADMIN',
        group: 'Gastos de administración',
        statementGroup: 'ADMIN_EXPENSES',
        parentCode: '4.5',
        isHeader: true,
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        resultFunction: 'ADMINISTRATION',
        notesGroup: 'Gastos',
        annexGroup: 'Gastos por función',
        profile: 'NONPROFIT',
    },
    {
        code: '4.5.20.01',
        name: 'Gastos de conducción institucional',
        kind: 'EXPENSE',
        section: 'ADMIN',
        group: 'Gastos de administración',
        statementGroup: 'ADMIN_EXPENSES',
        parentCode: '4.5.20',
        currentClassification: 'NOT_APPLICABLE',
        monetaryClassification: 'NON_MONETARY',
        cashFlowCategory: 'OPERATING',
        resultFunction: 'ADMINISTRATION',
        annexGroup: 'Gastos por función',
        profile: 'NONPROFIT',
    },
]

/** Catálogo completo, indexado por perfil. COMMERCIAL es el núcleo del seed. */
export const SECTOR_CATALOG: Record<string, SectorAccountDefinition[]> = {
    COMMERCIAL: [],
    SERVICES,
    INDUSTRIAL,
    AGRICULTURAL,
    NONPROFIT,
}

export const ALL_SECTOR_ACCOUNTS: SectorAccountDefinition[] = [
    ...SERVICES,
    ...INDUSTRIAL,
    ...AGRICULTURAL,
    ...NONPROFIT,
]
